Customize configs

diff --git a/bin/restore_backup b/bin/restore_backup
--- a/bin/restore_backup
+++ b/bin/restore_backup
@@ -2,57 +2,57 @@
 
 # Performs restoration of backup data.
 
-read -p "Has machine been rebooted since install (y/n)? " mac_os_reboot
+# read -p "Has machine been rebooted since install (y/n)? " mac_os_reboot
 
-if [[ "$mac_os_reboot" != "y" ]]; then
-  printf "ERROR: System or shell must be rebooted to leverage newly installed software.\n"
-  exit 1
-fi
+# if [[ "$mac_os_reboot" != "y" ]]; then
+#   printf "ERROR: System or shell must be rebooted to leverage newly installed software.\n"
+#   exit 1
+# fi
 
-read -p "Where is the backup volume (Example: \"/Volumes/alchemist\")? " mac_os_backup_root
+# read -p "Where is the backup volume (Example: \"/Volumes/alchemist\")? " mac_os_backup_root
 
-if [[ ! -e "$mac_os_backup_root" ]]; then
-  printf "ERROR: Backup volume cannot be found: $mac_os_backup_root\n"
-  exit 1
-fi
+# if [[ ! -e "$mac_os_backup_root" ]]; then
+#   printf "ERROR: Backup volume cannot be found: $mac_os_backup_root\n"
+#   exit 1
+# fi
 
-mkdir -p log
+# mkdir -p log
 
-rsync \
-  --rsync-path="sudo rsync" \
-  --perms \
-  --recursive \
-  --compress \
-  --numeric-ids \
-  --links \
-  --hard-links \
-  --files-from="$MAC_OS_CONFIG_PATH/lib/restore.bom" \
-  --log-file="log/restore.log" \
-  --human-readable \
-  --verbose \
-  "$mac_os_backup_root/" /
+# rsync \
+#   --rsync-path="sudo rsync" \
+#   --perms \
+#   --recursive \
+#   --compress \
+#   --numeric-ids \
+#   --links \
+#   --hard-links \
+#   --files-from="$MAC_OS_CONFIG_PATH/lib/restore.bom" \
+#   --log-file="log/restore.log" \
+#   --human-readable \
+#   --verbose \
+#   "$mac_os_backup_root/" /
 
-# Newsyslog
-sudo cp -p "$mac_os_backup_root/etc/newsyslog.d/alchemists.conf" "/etc/newsyslog.d"
-sudo cp -p "$mac_os_backup_root/etc/newsyslog.d/homebrew.conf" "/etc/newsyslog.d"
+# # Newsyslog
+# sudo cp -p "$mac_os_backup_root/etc/newsyslog.d/alchemists.conf" "/etc/newsyslog.d"
+# sudo cp -p "$mac_os_backup_root/etc/newsyslog.d/homebrew.conf" "/etc/newsyslog.d"
 
-# Dotfiles
-(
-  cd "$HOME/Dropbox/Development/OSS/dotfiles"
-  bin/run l
-)
+# # Dotfiles
+# (
+#   cd "$HOME/Dropbox/Development/OSS/dotfiles"
+#   bin/run l
+# )
 
-# Ruby
-(
-  cd "$HOME/Dropbox/Development/OSS/ruby_setup"
-  bin/run i
-)
+# # Ruby
+# (
+#   cd "$HOME/Dropbox/Development/OSS/ruby_setup"
+#   bin/run i
+# )
 
-# Sublime Text
-(
-  cd "$HOME/Dropbox/Development/OSS/sublime_text_setup"
-  bin/run l
-)
+# # Sublime Text
+# (
+#   cd "$HOME/Dropbox/Development/OSS/sublime_text_setup"
+#   bin/run l
+# )
 
-# Duti
-duti "$HOME/.config/duti/configuration.duti"
+# # Duti
+# duti "$HOME/.config/duti/configuration.duti"
